name: Dev Branch Deployment
on:
  push:
    branches:
      - dev
jobs:
  deployToHeroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
    - name: Deploying to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git config --global user.email "khan.t.29@gmail.com"
        git config --global user.name "Tabrez Khan"
        git fetch --all --unshallow
        git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/dev:refs/heads/master