name: Dev Branch Deployment
on:
  push:
    branches:
      - dev
jobs:
  deployToHeroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
    - name: Deploying to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        echo $HEROKU_APP_NAME
        echo "Hello World"
        git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/dev:master